# This is a basic workflow to help you get started with Actions

name: PR Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      
      # Runs a single command using the runners shell
      - name: Read PR body
        run: echo Hello, world!
        
      # Runs a single command using the runners shell
      - name: Install Salesforce CLI
        run: npm install sfdx-cli --global
        
      # Runs a single command using the runners shell
      - name: Install sfdx GIt Delta
        run: echo Hello, world!
        
      # Runs a single command using the runners shell
      - name: Install java
        run: echo Hello, world!
        
      # Runs a single command using the runners shell
      - name: Install SFDX Scanner
        run: echo Hello, world!
        
      # Runs a single command using the runners shell
      - name: Polpulate Auth file with SFDX URL and credential
        run: echo Hello, world!
      # Runs a single command using the runners shell
      - name: Authenticate Org
        run: echo Hello, world!
        
      # Runs a single command using the runners shell
      - name: Create Delta Package for New, modified or deleted Metadata
        run: echo Hello, world!
        
      # Runs a single command using the runners shell
      - name: Scan Code
        run: echo Hello, world!
     
      # Runs a single command using the runners shell
      - name: Upload SARIF file
        run: echo Hello, world! 
        
      # Runs a single command using the runners shell
      - name: Checkonly deploy delta changes - Run Specified Test
        run: echo Hello, world! 
      # Runs a single command using the runners shell
      - name: Checkonly deploy delta changes - Run all test
        run: echo Hello, world! 
     
     # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
